#! /bin/bash

sxhkd &
unagi &
nm-applet &
touch /tmp/barHidden
monitorUpdate

if [ "`xrandr --listmonitors | head -1 | rev | cut -c 1`" -eq 1 ]; then
       singlemon 
else
       multimon
fi

$HOME/.config/polybar/launch.sh &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus	button1

bspc config right_padding -14
bspc config left_padding -14
bspc config top_padding -14

# Scratchpad
bspc rule -a scratchpad sticky=on state=floating hidden=on
termite --hold -e scratch &
