#! /bin/bash

sxhkd &
redshift &
picom -b
nm-applet &
touch /tmp/barHidden
autocutsel -s PRIMARY -fork
autocutsel -s CLIPBOARD -fork
udiskie &

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > /tmp/ssh-agent-pid
fi
if [[ ! "$SSH_AUTH_SOCK" ]]; then
    eval "$(</tmp/ssh-agent-pid)"
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus	button1

bspc config right_padding -14
bspc config left_padding -14
bspc config top_padding -14

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

monitor-update
monitor-apply
monitor-bspwm

$HOME/.config/polybar/launch.sh &

# Scratchpad
bspc rule -a scratchpad sticky=on state=floating hidden=on
termite --hold -e scratch &
