#!/bin/bash

XSECURELOCK_SAVER=saver_mplayer \
    XSECURELOCK_PASSWORD_PROMPT=time \
    XSECURELOCK_DISCARD_FIRST_KEYPRESS=0 \
    XSECURELOCK_LIST_VIDEOS_COMMAND="find /opt/ATV4 -type l,f" \
    xsecurelock

