#!/bin/sh

if [ $# == 0 ]; then
    xrandr --listactivemonitors | tail -n +2 | cut -d ' ' -f 6
    exit
elif [ $# != 1 ]; then
    echo "Must supply 0 or 1 arguments."
    exit
fi
if [ $1 = "primary" ]; then
    xrandr --listactivemonitors | grep "*" | cut -d ' ' -f 6
elif [ $1 = "connected" ]; then
    xrandr --listactivemonitors | tail -n +2 | cut -d ' ' -f 6
elif ! expr "$1" : '[0-9][0-9]*$'>/dev/null; then
    echo "Argument must be a number or 'primary' or 'connected'"
elif [ $1 -lt 1 ]; then
    echo "Argument must be greater than zero"
else
    xrandr --listactivemonitors | tail -n +2 | cut -d ' ' -f 6 | sed -n $1p
fi

