#!/bin/sh

monitor-update

PREV_M=`monitor-get 1`
xrandr --output $PREV_M --auto

for MONITOR in $(monitor-get | cut -d ' ' -f 1 | sed 1d); do
    xrandr --output $MONITOR --auto --right-of $PREV_M
    PREV_M=$MONITOR
done

xrandr --output $(monitor-get primary) --primary

feh --bg-scale $HOME/.dog.png
