#! /bin/sh


xrandr | grep -w "connected" | head -1 | cut -d ' ' -f 1 > /tmp/primaryMonitor

if [ "`xrandr | grep -w "connected" | wc -l`" -eq 2 ]; then
        xrandr | grep -w "connected" | tail -1 | cut -d ' ' -f 1 > /tmp/secondaryMonitor
else
        echo " " > /tmp/secondaryMonitor
fi
