#!/bin/sh

if [ $# == 0 ]; then
    cat /tmp/monitorList
    exit
elif [ $# != 1 ]; then
    echo "Must supply 0 or 1 arguments."
    exit
fi

if ! expr "$1" : '[0-9][0-9]*$'>/dev/null; then
    echo "Argument must be a number"
elif [ $1 -lt 1 ]; then
    echo "Argument must be greater than zero"
else
    sed -n $1p /tmp/monitorList
fi

