#!/bin/sh

monitorUpdate

pMon=`cat /tmp/primaryMonitor`
sMon=`cat /tmp/secondaryMonitor`

xrandr --output $pMon --auto --output $sMon --auto --right-of $pMon
bspc monitor $pMon -d I II III IV V
bspc monitor $sMon -d VI VII VIII IX X
feh --bg-scale /home/eetu/.dog.png
