#!/bin/sh

monitorUpdate

monCount=`xrandr | grep -w "connected" | wc -l`
pMon=`cat /tmp/primaryMonitor`
sMon=`cat /tmp/secondaryMonitor`
tMon=`cat /tmp/thirdMonitor`

if [ $monCount -eq 2 ]; then
    xrandr --output $pMon --auto --output $sMon --auto --right-of $pMon
    bspc monitor $pMon -d I II III IV V
    bspc monitor $sMon -d VI VII VIII IX X
elif [ $monCount -eq 3 ]; then
    xrandr --output $pMon --auto --output $sMon --auto --right-of $pMon --output $tMon --auto --left-of $pMon
    bspc monitor $pMon -d I II III IV V
    bspc monitor $sMon -d VI VII VIII
    bspc monitor $tMon -d IX X
else
    xrandr --output $pMon --auto --output $sMon --off --output $tMon --off
fi

feh --bg-scale /home/eetu/.dog.png
