#! /bin/sh


xrandr | grep -w "connected" | cut -d ' ' -f 1 > /tmp/monitorList
PRIMARY_MONITOR="$(bspc query -M --names -m focused)"
echo $PRIMARY_MONITOR > /tmp/primaryMonitor
xrandr --output $PRIMARY_MONITOR --primary
sed -i '/'"$PRIMARY_MONITOR"'/d' /tmp/monitorList
touch /tmp/secondaryMonitor
touch /tmp/thirdMonitor

if [ "`xrandr | grep -w "connected" | wc -l`" -eq 2 ]; then
    sed -n 1p /tmp/monitorList > /tmp/secondaryMonitor
    rm /tmp/thirdMonitor
elif [ "`xrandr | grep -w "connected" | wc -l`" -eq 3 ]; then
    sed -n 1p /tmp/monitorList > /tmp/secondaryMonitor
    sed -n 2p /tmp/monitorList > /tmp/thirdMonitor
else
    rm /tmp/secondaryMonitor
    rm /tmp/thirdMonitor
fi
