#! /bin/sh

monitorUpdate

pMon=`cat /tmp/primaryMonitor`
sMon=`cat /tmp/secondaryMonitor`

xrandr --output $pMon --auto --output $sMon --off

bspc monitor $sMon -r
bspc monitor $pMon -d I II III IV V VI VII VIII IX X
