#! /bin/sh

monitorUpdate

pMon=`cat /tmp/primaryMonitor`
sMon=`cat /tmp/secondaryMonitor`
tMon=`cat /tmp/thirdMonitor`

xrandr --output $pMon --auto --output $sMon --off --output $tMon --off

bspc monitor $tMon -r
bspc monitor $sMon -r
bspc monitor $pMon -d I II III IV V VI VII VIII IX X
