#!/bin/sh

monitorUpdate

pMon=`cat /tmp/primaryMonitor`
sMon=`cat /tmp/secondaryMonitor`

if xrandr | grep "$sMon connected ("; then
	multimon
	resolution=`xrandr | grep $sMon | cut -f1 -d"+"`
	notify-send "$resolution" --icon=video-display
elif xrandr | grep "$sMon disconnected"; then
	notify-send "No Monitor Connected" --icon=video-display
else
	singlemon
	notify-send "$sMon Disconnected" --icon=video-display
fi
